// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbuqlgdbrjplyjlyfjky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidXFsZ2RicmpwbHlqbHlmamt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MjE5NTEsImV4cCI6MjA0OTQ5Nzk1MX0.4xAiQRRp5iMZs_-HOaDR-Gtf1d1H9GNAIIH9ABUUE_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);